apiVersion: v1
kind: ConfigMap
metadata:
  name: app-content
  namespace: import-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Fleet Demo - Imported Cluster</title>
      <style>
        body {
          font-family: Arial;
          background: #1a0a2e;
          color: white;
          text-align: center;
          padding: 50px;
          margin: 0;
        }
        h1 { color: #ff6b6b; }
        .box {
          background: #2d1b4e;
          padding: 25px;
          margin: 20px auto;
          max-width: 600px;
          border-radius: 12px;
          border: 2px solid #ff6b6b;
        }
        .green { color: #00ff88; font-size: 1.4em; font-weight: bold; }
        .badge {
          background: #ff6b6b;
          color: black;
          padding: 6px 20px;
          border-radius: 20px;
          font-weight: bold;
          display: inline-block;
          margin: 10px;
        }
      </style>
    </head>
    <body>
      <h1>🚀 Fleet GitOps Demo</h1>
      <div class="box">
        <p class="green">✅ IMPORTED CLUSTER</p>
        <div class="badge">imported-k3s | 10.0.33.149</div>
        <p>This app was deployed by Fleet automatically</p>
        <p>Source: Same GitHub Repository</p>
        <p>No kubectl command was run manually</p>
      </div>
      <div class="box">
        <h3>GitOps Power:</h3>
        <p>ONE GitHub repo → TWO clusters</p>
        <p>Push once → Both clusters updated</p>
        <p>This is how Netflix, Flipkart deploy</p>
      </div>
      <div class="box">
        <p>👩‍💻 Anjali Tripathi | B2255R10106169</p>
        <p>AKS University | BTech CSE 8th Sem</p>
      </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-app
  namespace: import-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleet-app
  template:
    metadata:
      labels:
        app: fleet-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app-content
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-app-svc
  namespace: import-app
spec:
  selector:
    app: fleet-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
